site_name: ObsCure Docs
nav:
  - Home: index.md
  - Introduction: intro.md
  - Items: items.md
  - Events: events.md
  - File Formats: formats.md
  - Binaries info: binaries.md
  - Constants & Types: constants.md
  - About: about.md
theme: readthedocs
